Eclipse/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eclipse_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eclipse_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('distros/<int:pk>/', views.distro_detail, name='distro_detail'),
    path('distros/', views.distros_list, name='distros_list'),
    path('documentation/<int:pk>/', views.documentation_detail, name='documentation_detail'),
    path('documentation/', views.documentation_list, name='documentation_list'),
    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/<str:username>/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/<int:pk>/', views.article_detail, name='article_detail'),
    path('articles/create/', views.create_article, name='create_article'),
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eclipse_app/models.py
from django.db import models
from django.core.exceptions import ValidationError
from PIL import Image
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
import os
from django.core.validators import MinLengthValidator


class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name='Тег')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class CurrentVersion(models.Model):
    version = models.CharField(max_length=50, verbose_name='Версия')
    current_version = models.CharField(max_length=50, verbose_name='Текущая версия')
    code_name = models.CharField(max_length=128, verbose_name='Кодовое имя')
    architectures = models.CharField(max_length=55, verbose_name='Количество поддерживаемых архитектур')
    packages = models.CharField(max_length=55, verbose_name='Количество пакетов')
    release_date = models.DateField(verbose_name='Дата выпуска')
    support_end_date = models.DateField(verbose_name='Дата окончания поддержки', blank=True, null=True)
    full_support_end_date = models.DateField(verbose_name='Дата окончания длительной поддержки', blank=True, null=True)
    distribution = models.ForeignKey('LinuxDistribution', on_delete=models.CASCADE, related_name='current_versions', verbose_name='Дистрибутив')

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'


def validate_square_image(image):
    if image.width != image.height:
        raise ValidationError("Стороны изображения должны быть равны!")


def distro_image_upload_path(instance, filename):
    return f'distros/{instance.name}/{filename}'


class LinuxDistribution(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField(validators=[validate_square_image], upload_to=distro_image_upload_path, verbose_name='Изображение')
    short_description = models.TextField(max_length=255, verbose_name='Краткое описание')
    official_website = models.URLField(verbose_name='Официальный сайт')
    release_date = models.DateField(verbose_name='Дата выпуска')
    based_on = models.CharField(max_length=100, verbose_name='Основа для данной ОС')
    description = models.TextField(verbose_name='Описание')
    history = models.TextField(verbose_name='История создания')
    features = models.TextField(verbose_name='Особенности')
    tags = models.ManyToManyField(Tag, related_name='distributions', verbose_name='Теги')

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img_path = self.image.path
            img = Image.open(img_path)

            img = img.resize((600, 600), Image.Resampling.LANCZOS)

            img.save(img_path)

    class Meta:
        verbose_name = 'Дистрибутив Linux'
        verbose_name_plural = 'Дистрибутивы Linux'


def distro_step_upload_path(instance, filename):
    return f'installation_steps/{instance.distribution.name}/{filename}'


class InstallationStep(models.Model):
    distribution = models.ForeignKey(LinuxDistribution, on_delete=models.CASCADE, related_name='installation_steps',
                                     verbose_name='Дистрибутив')
    step_number = models.IntegerField(verbose_name='Номер шага')
    step_text = models.TextField(verbose_name='Текст шага')
    step_image = models.ImageField(upload_to=distro_step_upload_path, verbose_name='Изображение шага', blank=True)

    def __str__(self):
        return f"{self.distribution.name} - Шаг {self.step_number}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.step_image:
            img_path = self.step_image.path
            img = Image.open(img_path)

            img = img.resize((800, 450), Image.Resampling.LANCZOS)

            img.save(img_path)

    class Meta:
        verbose_name = 'Шаг установки'
        verbose_name_plural = 'Шаги установки'


def documentation_image_upload_path(instance, filename):
    return f'documentation/{instance.title}/{filename}'


def documentation_pdf_upload_path(instance, filename):
    return f'documentation_pdf/{instance.title}/{filename}'


class Documentation(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название документации')
    content = RichTextField(verbose_name='Контент документации', blank=True, null=True)
    image = models.ImageField(validators=[validate_square_image], upload_to=documentation_image_upload_path, default='/')
    author = models.CharField(max_length=255, verbose_name='Автор', default='Нет')
    year = models.CharField(max_length=16, verbose_name='Год выпуска', default='2001', blank=True, null=True)
    topic = models.CharField(max_length=255, verbose_name='Тема', default='Нет', blank=True, null=True)
    pdf_only = models.BooleanField(verbose_name='True = Только в PDF', default=False)
    pdf = models.FileField(verbose_name='PDF', upload_to=documentation_pdf_upload_path, blank=True, null=True)

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img_path = self.image.path
            img = Image.open(img_path)

            img = img.resize((600, 600), Image.Resampling.LANCZOS)

            img.save(img_path)

    class Meta:
        verbose_name = 'Документация'
        verbose_name_plural = 'Документация'
        unique_together = (('title', 'content'),)


def profile_image_upload_path(instance, filename):
    return f'profile_image/{instance.user.username}/{filename}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='USER')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    profile_image = models.ImageField(
        upload_to=profile_image_upload_path,
        null=True,
        blank=True,
        verbose_name='Изображение профиля',
        validators=[validate_square_image]
    )
    changed = models.BooleanField(verbose_name='Подтверждены изменения', default=False)

    def __init__(self, *args, **kwargs):
        super(Profile, self).__init__(*args, **kwargs)
        self._original_birth_date = self.birth_date
        self._original_profile_image = self.profile_image
        self._original_first_name = self.user.first_name if self.user else None
        self._original_last_name = self.user.last_name if self.user else None
        self._original_email = self.user.email if self.user else None

    def save(self, *args, **kwargs):
        if (self.birth_date != self._original_birth_date or
                self.profile_image != self._original_profile_image or
                (self.user and (self.user.first_name != self._original_first_name or
                                self.user.last_name != self._original_last_name or
                                self.user.email != self._original_email))):
            self.changed = True

        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


def article_image_upload_path(instance, filename):
    return f'article_image/{instance.title}/{filename}'


class ArticleTag(models.Model):
    name = models.CharField(max_length=50, verbose_name='Тег')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег для статьи'
        verbose_name_plural = 'Теги для статей'


class Article(models.Model):
    title = models.CharField(max_length=55, verbose_name='Название статьи')
    description = models.TextField(max_length=256, validators=[MinLengthValidator(200, message="Кол-во символов: min:200-max:255")], verbose_name='Описание', blank=True, null=True)
    content = RichTextField(verbose_name='Контент статьи')
    image = models.ImageField(validators=[validate_square_image], upload_to=article_image_upload_path, verbose_name='Изображение статьи')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан в')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Отредактирован в')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    tags = models.ManyToManyField(ArticleTag, related_name='articles', verbose_name='Теги')
    verification = models.BooleanField(verbose_name='Верификация', default=False)

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img_path = self.image.path
            img = Image.open(img_path)

            img = img.resize((600, 600), Image.Resampling.LANCZOS)

            img.save(img_path)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

eclipse_app/views.py
import time
from datetime import datetime
from .models import *
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth.views import LoginView


def article_list(request):
    articles = Article.objects.all()

    search_query = request.GET.get('search', '')
    sort_option = request.GET.get('sort', '')
    count = 0
    count_diff = 0

    if search_query:
        articles = articles.filter(title__icontains=search_query)
        count = articles.count()
        count_diff = count % 10

    if sort_option:
        articles = articles.order_by(sort_option)

    return render(request, 'article_list.html', {
        'articles': articles,
        'search_query': search_query,
        'sort_option': sort_option,
        'count': count,
        'count_diff': count_diff,
        'title': 'Список статей'
    })


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    verification = article.verification
    if verification:
        return render(request, 'article_detail.html', {'article': article, 'title': article.title})
    else:
        return redirect('article_list')


def create_article(request):
    plus_18_year_old = False
    current_user = request.user
    current_time_ms = int(time.time() * 1000)
    user_old_str = str(current_user.profile.birth_date).replace('-', '.')
    dt = datetime.strptime(user_old_str, "%Y.%m.%d")
    user_old_ms = int(dt.timestamp() * 1000)
    if current_time_ms - user_old_ms >= 568036800000:
        plus_18_year_old = True
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = current_user
            article.save()
            return redirect('profile', username=request.user.username)
    else:
        form = ArticleForm()

    return render(request, 'create_article.html', {'form': form, 'old': plus_18_year_old})


@login_required
def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    if user != request.user:
        return redirect('profile', username=request.user.username)
    title = f"{user.username}#{user.id}"
    return render(request, 'profile.html', {'user': user, 'title': title})


@login_required
def edit_profile(request, username):
    user = get_object_or_404(User, username=username)

    if user != request.user:
        return redirect('profile', username=user.username)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('profile', username=user.username)
    else:
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)

    return render(request, 'edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'title': f"{user.username} Редактирование",
    })


class CustomLoginView(LoginView):
    def get_success_url(self):
        return reverse('profile', kwargs={'username': self.request.user.username})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Аккаунт {username} успешно создан!')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form, 'title': 'Регистрация'})


def documentation_detail(request, pk):
    documentation = get_object_or_404(Documentation, pk=pk)
    return render(request, 'documentation_detail.html', {'documentation': documentation, 'title': documentation.title})


def documentation_list(request):
    documentations = Documentation.objects.all()

    search_query = request.GET.get('search', '')
    sort_option = request.GET.get('sort', '')
    count = 0
    count_diff = 0

    if search_query:
        documentations = documentations.filter(title__icontains=search_query)
        count = documentations.count()
        count_diff = count % 10

    if sort_option:
        documentations = documentations.order_by(sort_option)

    return render(request, 'documentation_list.html', {
        'documentations': documentations,
        'search_query': search_query,
        'sort_option': sort_option,
        'count': count,
        'count_diff': count_diff,
        'title': 'Справочник по Linux'
    })


def distro_detail(request, pk):
    distribution = get_object_or_404(LinuxDistribution, pk=pk)
    return render(request, 'distro_detail.html', {'distribution': distribution, 'title': distribution.name})


# def distros_list(request):
#     distributions = LinuxDistribution.objects.all()
#
#     search_query = request.GET.get('search')
#     if search_query:
#         distributions = distributions.filter(name__icontains=search_query)
#
#     sort_option = request.GET.get('sort')
#     if sort_option == 'name':
#         distributions = distributions.order_by('name')
#     elif sort_option == '-name':
#         distributions = distributions.order_by('-name')
#
#     selected_tag = request.GET.get('tag')
#     if selected_tag:
#         distributions = distributions.filter(tags__name=selected_tag)
#
#     tags = Tag.objects.all()
#
#     return render(request, 'distros_list.html', {
#         'distributions': distributions,
#         'tags': tags,
#         'selected_tag': selected_tag,
#         'search_query': search_query,
#         'sort_option': sort_option,
#         'title': 'Список дистрибутивов'
#     })


def distros_list(request):
    distributions = LinuxDistribution.objects.all()

    search_query = request.GET.get('search', '')
    sort_option = request.GET.get('sort', '')
    selected_tag = request.GET.get('tag', '')
    count = 0
    count_diff = 0

    if search_query:
        distributions = distributions.filter(name__icontains=search_query)
        count = distributions.count()
        count_diff = count % 10

    if selected_tag:
        distributions = distributions.filter(tags__name=selected_tag)

    if sort_option:
        distributions = distributions.order_by(sort_option)

    tags = Tag.objects.all()

    return render(request, 'distros_list.html', {
        'distributions': distributions,
        'tags': tags,
        'selected_tag': selected_tag,
        'search_query': search_query,
        'sort_option': sort_option,
        'count': count,
        'count_diff': count_diff,
        'title': 'Список дистрибутивов'
    })


def home(request):
    return render(request, 'base.html', {'title': 'Главная'})

eclipse_app/templates/article_detail.html
{% extends 'base.html' %}
{% load tz %}

{% block content %}
<div class="content-distro">
        <div class="main-distro-content">
            <div class="back-btn"><a href="{% url 'article_list' %}"><i class="fa-solid fa-angle-left fa-xl"></i> <strong>Назад</strong></a></div>
            <br>
            <div class="distro-header" style="flex-wrap: nowrap;">
                <img class="img-logo" src="{{ article.image.url }}" alt="{{ article.title }}">
                <div class="div-text">
                    <p class="text-larger margin-bottom-20 max-600">{{ article.title }}</p>
                    <p class="text-large text-666"><strong><i class="fa-solid fa-user fa-xl" style="color: #74C0FC;"></i>&nbsp;&nbsp;<span>Автор:</span></strong><span>&nbsp;{{ article.author.username }}#{{ article.author.id }}</span></p>
                    <p class="text-large text-666"><strong><i class="fa-solid fa-calendar-days fa-xl" style="color: #74C0FC;"></i>&nbsp;&nbsp;<span>Дата написания статьи:</span></strong><span>&nbsp;{{ article.created_at|localtime|date:"H:i, d.m.Y" }}</span></p>
                    <p class="text-large text-666"><strong><i class="fa-solid fa-tags fa-xl" style="color: #74C0FC;"></i>&nbsp;&nbsp;<span>{{ article.tags.all|join:", " }}</span></strong></p>
                </div>
            </div>
        </div>
        <div class="second-distro-content">
            <div id="content" class="tab-content active">
                <p class="text-header-tab text-large-left">Статья</p>
                <hr>
                <br>
                <p class="text-m">{{ article.content|safe }}</p>
            </div>
            </div>
</div>
{% endblock %}

eclipse_app/templates/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h1 class="page-title">{{ title }}</h1>
        <div class="filter-bar">
            <form method="GET" action="{% url 'article_list' %}" class="filter-form">
                <!-- Поиск по названию -->
                <label>Поиск:
                    <input type="text" name="search" placeholder="Поиск по названию..." value="{{ search_query }}" class="search-input">
                </label>

                <!-- Сортировка -->
                <label>Сортировка:
                    <select name="sort" class="sort-select">
                        <option value="" {% if not sort_option %}selected{% endif %}>По умолчанию</option>
                        <option value="title" {% if sort_option == "title" %}selected{% endif %}>По названию (А-Я)</option>
                        <option value="-title" {% if sort_option == "-title" %}selected{% endif %}>По названию (Я-А)</option>
                        <option value="created_at" {% if sort_option == "created_at" %}selected{% endif %}>По дате (сначала новые)</option>
                        <option value="created_at" {% if sort_option == "-created_at" %}selected{% endif %}>По дате (сначала старые)</option>
                    </select>
                </label>

                <div class="separator"></div>

                <button type="submit" class="filter-button">Применить</button>
            </form>
        </div>

        <div class="sort-x">
            {% if sort_option %}
                <p>Сортировка:
                    {% if sort_option == 'title' %}
                         <span class="sort-list">По названию (А-Я)
                             <a class="h_xmark" href="?{% if search_query %}search={{ search_query }}&{% endif %}">
                             <i class="fa-solid fa-xmark"></i>
                             </a>
                         </span>
                    {% elif sort_option == '-title' %}
                         <span class="sort-list">По названию (Я-А)
                             <a class="h_xmark" href="?{% if search_query %}search={{ search_query }}&{% endif %}">
                             <i class="fa-solid fa-xmark"></i>
                             </a>
                         </span>
                    {% endif %}
                </p>
            {% endif %}
        </div>

        <div class="found">
            <br>
            {% if search_query %}
                {% if count_diff == 1 %}
                    <p>По запросу <strong>{{ search_query }}</strong> найден {{ count }} результат</p>
                {% endif %}
                {% if count_diff == 2 or count_diff == 3 or count_diff == 4 %}
                    <p>По запросу <strong>{{ search_query }}</strong> найдено {{ count }} результата</p>
                {% endif %}
                {% if count_diff > 4 %}
                    <p>По запросу <strong>{{ search_query }}</strong> найдено {{ count }} результатов</p>
                {% endif %}
                {% if count == 0 %}
                    <p>По запросу <strong>{{ search_query }}</strong> ничего не найдено</p>
                {% endif %}
            {% endif %}
        </div>

        {% if search_query or sort_option %}
            <br>
            <div class="clear-filters">
                <a href="{% url 'article_list' %}" class="clear-filters-button">Сбросить все фильтры</a>
            </div>
        {% endif %}

        <div style="margin-bottom: -15px;">
            <br>
            <a class="create-article-btn-list" href="{% url 'create_article' %}"><i class="fa-solid fa-pen"></i> Добавить статью</a>
        </div>

        <div class="distro-grid">
            {% for article in articles %}
                {% if article.verification is True %}
                    <div class="distro-item">
                        <a href="{% url 'article_detail' article.pk %}">
                            <div class="distro-image">
                                {% if article.image %}
                                    <img src="{{ article.image.url }}" alt="{{ article.title }}">
                                {% else %}
                                    <img src="{% static 'images/notfound.png' %}" alt="Нет изображения">
                                {% endif %}
                            </div>
                            <div class="distro-info">
                                <h2>{{ article.title }}</h2>
                                <div class="distro-info-mini">
                                    <p style="margin-bottom: 10px;">{{ article.description }}..</p>
                                    <p class="border-top">Автор: <strong>{{ article.author }}</strong></p>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

eclipse_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/6541b5e2da.js" crossorigin="anonymous"></script>
    <title>
        {% block title %}Eclipse |
            {% if title %}
                {{ title }}
            {% else %}
                Авторизация
            {% endif %}
        {% endblock %}
    </title>
</head>
<body>
    <div class="page-container">
        <div class="content-wrapper">
            <header>
                <nav>
                    <p class="nav-item logo"><a href="{% url 'home' %}">Eclipse</a></p>
                    <p class="nav-item nav-item-mini"><a href="{% url 'distros_list' %}">Список дистрибутивов Linux</a></p>
                    <p class="nav-item nav-item-mini"><a href="{% url 'documentation_list' %}">Справочник по Linux</a></p>
                    <p class="nav-item nav-item-mini"><a href="{% url 'article_list' %}">Статьи про Linux</a></p>
                    {% if user.is_authenticated is False %}
                        <p class="nav-item nav-item-mini"><a href="{% url 'login' %}">Авторизация</a></p>
                        <p class="nav-item nav-item-mini"><a href="{% url 'register' %}">Регистрация</a></p>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <p class="nav-item nav-item-mini"><a href="{% url 'profile' user.username %}">{{ user.username.capitalize }}</a></p>
                    {% endif %}
                </nav>
            </header>
            <main>
                <br><br>
                {% block content %}{% endblock %}
                {% block extra_scripts %}{% endblock %}
            </main>
        </div>
        <footer>
            <p style="text-align: center">© 2024 Eclipse</p>
        </footer>
    </div>
</body>
</html>

eclipse_app/templates/create_article.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <br>
    <div class="create-article-container">
        <h2 style="text-align: center; margin-top: 0;" class="page-title">Создание новой статьи</h2>
        {% if user.is_authenticated %}
            {% if user.profile.changed is True and user.first_name is not None and user.last_name is not None and user.email is not None and user.profile.birth_date is not None and user.first_name != "" and user.last_name != "" and user.email != "" and user.profile.birth_date != "" %}
                {% if old %}
                    <form method="POST" enctype="multipart/form-data" class="create-article-form">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_title">Название статьи</label>
                            {{ form.title }}
                            {% if form.title.errors %}
                                <div class="error-message">
                                    {{ form.title.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="id_description">Описание статьи</label>
                            {{ form.description }}
                            <div class="chars-counter"><span>Минимальное кол-во символов: 200, максимальное кол-во символов: 255. </span><span id="charCount">0</span><span>/255</span></div>
                            {% if form.description.errors %}
                                <div class="error-message">
                                    {{ form.description.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="id_content">Контент статьи</label>
                            {{ form.content }}
                            {% if form.content.errors %}
                                <div class="error-message">
                                    {{ form.content.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="id_image">Изображение статьи</label>
                            {{ form.image }}
                            {% if form.image.errors %}
                                <div class="error-message">
                                    {{ form.image.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="id_tags">Теги статьи</label>
                            <input type="text" id="id_tags" name="tags" placeholder="Введите теги через запятую" value="{{ form.tags.value|default_if_none:'' }}">
                            {% if form.tags.errors %}
                                <div class="error-message">
                                    {{ form.tags.errors }}
                                </div>
                            {% endif %}
                        </div>

                        <button type="submit" class="create-article-btn">Создать статью</button>
                    </form>
                    <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
                    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
                    <script>
                        function updateCharCount(textarea) {
                            document.getElementById('charCount').textContent = textarea.value.length;
                        }
                    </script>
                {% else %}
                    <h4 style="text-align: center;">Извините, но для публикации статей нужно быть старше 18-ти лет.</h4>
                {% endif %}
            {% else %}
                <h4 style="text-align: center;">Для публикации статьи вам необходимо отредактировать профиль. Заполните, пожалуйста, поля "Имя", "Фамилия", "Email" и "Дата рождения". <a class="user-profile-link" href="{% url 'edit_profile' user.username %}">Отредактировать профиль.</a></h4>
            {% endif %}
        {% else %}
            <h4 style="text-align: center;">Для публикации статьи вы должны быть авторизованы. <a class="user-profile-link" href="{% url 'login' %}">Авторизоваться.</a></h4>
        {% endif %}
    </div>
{% endblock %}

eclipse_app/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br><br><br>
<div class="edit-profile-container">
    <h2 style="margin-top: 0">Редактирование профиля</h2>
    <form method="POST" enctype="multipart/form-data" class="edit-profile-form">
        {% csrf_token %}
        <div class="form-group">
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
        </div>
        <button type="submit" class="save-btn">Сохранить изменения</button>
    </form>
    <a href="{% url 'profile' user.username %}" class="cancel-btn">Отмена</a>
</div>
{% endblock %}